commit/urls.py
# This file defines the URL schema for the site.

from django.conf.urls import patterns, url

from commit import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^about$', views.about, name='about'),
	url(r'^commit$', views.commit, name='commit'),
	url(r'^savecommit$', views.savecommit, name='savecommit'),
)

commitnow/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	url(r'', include('commit.urls', namespace='commit')),
    url(r'^admin/', include(admin.site.urls)),
)

commit/models.py
# This file defines the fields within the database for the User and Commit classes

import datetime

from django.db import models
from django.utils import timezone

# User is a record for each registered user.  For now, only limited data is stored in
# connection with each User.
class User(models.Model):
	username = models.CharField(max_length=20)
# When migrating it said that a default was required for each of these.  I do not know 
# why.
	firstname = models.CharField(max_length=50, default='Bob')  
	secondname = models.CharField(max_length=50, default='Bob')
	email = models.EmailField()
	def __unicode__(self):
		return self.username

# Commit is a record for each commitment.  Each Commit is linked to a User.
class Commit(models.Model):
 	commit_user = models.ForeignKey(User)
	commit_text = models.CharField(max_length=200)
	commit_date = models.DateTimeField()
	commit_privacy = models.BooleanField(default=False)
	def __unicode__(self):
		return self.commit_text
	def was_published_recently(self):
		return self.commit_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.short_description = 'Published recently?'
	was_published_recently.admin_order_field = 'commit_date'
	was_published_recently.boolean = True

commit/views.py
# This file defines the views for the website.

from django.http import HttpResponse
from django.shortcuts import render
from django.template import RequestContext, loader
from django.utils import timezone

from commit.models import Commit, User



def index(request):
	latest_commits = Commit.objects.order_by('-commit_date')[:5]
	template = loader.get_template('commit/index.html')
	context = RequestContext(request, {'latest_commits': latest_commits})
	return HttpResponse(template.render(context))

# I do not like how this works.  I need to find an alternative to 'render' which does not
# require a context.
def about(request):
	context = {'': ''}
	return render(request, 'commit/about.html', context)

# I do not like how this works.  I need to find an alternative to 'render' which does not
# require a context.	
def commit(request):
	context = {'': ''}
	return render(request, 'commit/commit.html', context)


def savecommit(request):
	default = User.objects.get(id=2) 	# sets user to Default pending login functionality
	new_commit = Commit(
		commit_user=default, 
		commit_text=request.POST['commit_text_input'], 
		commit_date=timezone.now()
		)
	new_commit.save()
	return index(request)  # I do not like how this works.  While the page returned is the
# index page, the URL shown is ./savecommit 	

commit/templates/commit/about.html
<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="description" content="Commit Now, Act Tomorrow - Commit Now, Act Tomorrow is a web application for setting and meeting daily priorities.">
	<meta name="author" content="Simon Leslie">
	<meta name="viewport" content="device-width">
	
	<title>Commit Now | Act Tomorrow</title>

{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'commit/css/normalise.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'commit/css/style.css' %}">
<!-- 
	<link type="image/png" rel="icon" href="img/favicon.ico">
 -->

	<!--[if lt IE 9]>
		<script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>

<body>

	<header>
		<div class="logo_wrapper">
		<a href="{% url 'commit:index' %}" id="logo" title="Commit Now">
			<h1>Commit now</h1>
			<h2>Act tomorrow</h2>
		</a>
		</div>
		<nav>
			<ul>
				<li>
					<a href="{% url 'commit:index' %}">Home</a>
				</li>	
				<li>
					<a href="{% url 'commit:commit' %}">Commit</a>
				</li>	
				<li>
					<a href="{% url 'commit:about' %}" class="selected">About</a>
				</li>
			</ul>
		</nav>	
	</header>
	
	<div class="wrapper">
		<div class="centre_wrap">
			<img src="{% static 'commit/img/about_photo.jpg' %}" alt="Photo of Simon" class="about_photo">
			<div class="about_text">
				<p>If you want to achieve something great, you need to start taking the small steps towards it now.  One of the best ways of doing this, is making a clear commitment, every day, to do something towards your goal tomorrow, and making that commitment public.  The accountability that comes with public commitments makes you more likely to achieve your stated goals. </p>
				<p>This simple web application is designed to help you achieve your goals by providing a forum in which you can publicly make a commitment to take action tomorrow in furtherance of your own goals.  You can make a commitment either anonymously or openly.  You will receive an email the next morning reminding you of your commitment and another at the end of the day, following up and asking whether you stood by your commitment. </p> 
			</div>
			<div class="about_text">
				<p>I created this web application for two reasons.  First, I think that it will be useful, not just for me, but for everyone who chooses to use it.  Second, because I wanted to learn how to make a simple web application.  The internet has changed all of our lives and has huge potential for further positive change - but it is only we that can create that change, one small step at a time.</p>  
			</div>
		</div>
	</div>
	
	
	<footer class="footer">
		<div class="social">
			<a href="https://www.facebook.com/s.t.leslie" target="_blank" class="social-btn facebook">Facebook</a>
			<a href="https://www.twitter.com/slezzer" target="_blank" class="social-btn twitter">Twitter</a>
		</div>	
		<div class="copyright">
					© 2014 Simon Leslie
		</div>
	</footer>
	
</body>
</html>

commit/templates/commit/commit.html
<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="description" content="Commit Now, Act Tomorrow - Commit Now, Act Tomorrow is a web application for setting and meeting daily priorities.">
	<meta name="author" content="Simon Leslie">
	<meta name="viewport" content="device-width">
	
	<title>Commit Now | Act Tomorrow</title>

{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'commit/css/normalise.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'commit/css/style.css' %}">
<!-- 
	<link type="image/png" rel="icon" href="img/favicon.ico">
 -->

	<!--[if lt IE 9]>
		<script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>

<body>

	<header>
		<div class="logo_wrapper">
		<a href="{% url 'commit:index' %}" id="logo" title="Commit Now">
			<h1>Commit now</h1>
			<h2>Act tomorrow</h2>
		</a>
		</div>
		<nav>
			<ul>
				<li>
					<a href="{% url 'commit:index' %}">Home</a>
				</li>	
				<li>
					<a href="{% url 'commit:commit' %}" class="selected">Commit</a>
				</li>	
				<li>
					<a href="{% url 'commit:about' %}">About</a>
				</li>
			</ul>
		</nav>	
	</header>
	
	<div class="form_wrap">
		<form action="{% url 'commit:savecommit' %}" method="post">
		{% csrf_token %}
			<label for:"commit_text_input" class="commit_label">Make a commitment</label>
			<textarea id="commit_text_input" name="commit_text_input" autofocus required rows="5" placeholder="Tomorrow, I will ..."></textarea>
<!-- THE PRIVACY SETTINGS DON'T WORK YET ...
			<fieldset class="privacy">
				<label class="small_label">Privacy setting:</label>
				<input type="radio" id="open" value="1" name="privacy" class="privacy_radio" checked><label for="False" class="small_label">Open</label>
				<input type="radio" id="anon" value="0" name="privacy" class="privacy_radio"><label for="True" class="small_label">Private</label>
			</fieldset>
 -->
			<button type="submit">Commit</button>
		</form>
	</div>
	
	<footer class="footer">
		<div class="social">
			<a href="https://www.facebook.com/s.t.leslie" target="_blank" class="social-btn facebook">Facebook</a>
			<a href="https://www.twitter.com/slezzer" target="_blank" class="social-btn twitter">Twitter</a>
		</div>	
		<div class="copyright">
					© 2014 Simon Leslie
		</div>
	</footer>
	
</body>
</html>

commit/templates/commit/index.html
<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="description" content="Commit Now, Act Tomorrow - Commit Now, Act Tomorrow is a web application for setting and meeting daily priorities.">
	<meta name="author" content="Simon Leslie">
	<meta name="viewport" content="device-width">
	
	<title>Commit Now | Act Tomorrow</title>

{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'commit/css/normalise.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'commit/css/style.css' %}">
<!-- 	<link type="image/png" rel="icon" href="img/favicon.ico"> -->

	<!--[if lt IE 9]>
		<script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>

<body>

	<header>
		<div class="logo_wrapper">
		<a href="{% url 'commit:index' %}" id="logo" title="Commit Now">
			<h1>Commit now</h1>
			<h2>Act tomorrow</h2>
		</a>
		</div>
		<nav>
			<ul>
				<li>
					<a href="{% url 'commit:index' %}" class="selected">Home</a>
				</li>	
				<li>
					<a href="{% url 'commit:commit' %}">Commit</a>
				</li>	
				<li>
					<a href="{% url 'commit:about' %}">About</a>
				</li>
			</ul>
		</nav>	
	</header>
	
	<div class="wrapper">

<!-- Latest_commits should include details of the five most recent commits.  Brief details
of each of these will be displayed.  If latest_commits does not exist, an error message 
will be displayed. -->

{% if latest_commits %}
	{% for commit in latest_commits %}
		<div class="commit_container">
			<div class="commit_text">{{ commit.commit_text }}</div>
			<div class="commit_user">{{ commit.commit_user }}</div>
			<div class="commit_date">{{ commit.commit_date }}</div>
		</div>
	{% endfor %}
{% else %}
		<div class="commit_container">
			<div class="commit_text">There are no commits in the database.<br>&nbsp;</div>
{% endif %}

	</div>
	
	<footer class="footer">
		<div class="social">
			<a href="https://www.facebook.com/s.t.leslie" target="_blank" class="social-btn facebook">Facebook</a>
			<a href="https://www.twitter.com/slezzer" target="_blank" class="social-btn twitter">Twitter</a>
		</div>	
		<div class="copyright">
					© 2014 Simon Leslie
		</div>
	</footer>
	
</body>
</html>